### ISSUE TITLE
Failed at the snappy@3.0.8 install script.

### ISSUE THREAD

**Issue by alabeduarte** [RenmanKang/KafkaWebMonitor#1]
Hey,

Seems like there is a dependency issue. Which is the recommended node.js version to build this project? Currently I'm using node `v5.7.1` and it's not working:

``` bash
...
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! snappy@3.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snappy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
...
```

Thanks

**Comment by RenmanKang** [comment]
This project has been tested on node v0.10.29, npm 1.4.14.
For node v5.7.x, please check the following:

First, the following modules may also be necessary to update to the latest node module.
- "deasync": "~0.0.10" -> "deasync": "0.1.4",
- "kafka-node": "0.2.26" -> "kafka-node": "0.3.2",
- "zookeeper": "3.4.6-4" -> "zookeeper": "3.4.6-8"  or "3.4.7-2"

Next, you may gcc, g++ program is required for the installation of kafka-node, zookeeper node modules.

**Comment by alabeduarte** [comment]
Thank you very much, worked with version v0.10.29. What I had to do though was change `conf/config.js` logger filename to a valid one.

Do you have an idea on how to fix this?

Thanks

**Comment by RenmanKang** [comment]
The purpose of conf/config.js file is for simply managing the configuration information.
So, you can change the path of the "logger filename" as you did.
Otherwise, you can create a logs directory in the root directory of the project.

In addition, you will be able to change all other configuration information, including the service port.

**Comment by alabeduarte** [comment]
Thank you.
